version: "3.8"
name: calendar

services:
  postgres:
    image: postgres:15.1
    container_name: pg-clndr
    environment:
      POSTGRES_USER: sys
      POSTGRES_PASSWORD: sys
      POSTGRES_DB: calendar
      PGDATA: /var/lib/postgresql/data/pgdata 
    ports:
      - "5434:5432"
    volumes:
    #  - /mnt/pod-store/pg-clndr:/var/lib/postgresql/data 
      - ../migrations/000_init.sql:/docker-entrypoint-initdb.d/init.sql
    network_mode: bridge
  postgres2:
    image: postgres:15.1
    container_name: pg-clndr2
    environment:
      POSTGRES_USER: sys
      POSTGRES_PASSWORD: sys
      POSTGRES_DB: calendar
      PGDATA: /var/lib/postgresql/data/pgdata 
    ports:
      - "5433:5432"
    volumes:
    #  - /mnt/pod-store/pg-clndr:/var/lib/postgresql/data 
      - ../migrations/000_init.sql:/docker-entrypoint-initdb.d/init.sql
    network_mode: bridge
