[logger]
level = "DEBUG"
depth = 5

[storage]
type = "postgres"

[store-postgres]
host = "localhost"
port = 5432
dbname = "calendar"
username = "clndr"
password = "clndr"

[http-server]
host = "localhost"
port = 1234
timeout = 10


